import fs from 'node:fs';
import path from 'node:path';
import kleur from 'kleur';
import { readState, SurfaceName } from '../state.js';
import {
  claudeUserMd,
  vscodePromptsDir,
  codexHome,
  userGeneratedRoot,
} from '../paths.js';

const ALL: SurfaceName[] = ['claude', 'copilot-vscode', 'copilot-cli', 'codex'];

export interface StatusOptions {
  json?: boolean;
}

export function status(opts: StatusOptions = {}): void {
  const state = readState();
  const profileNames = Object.keys(state.profiles).sort();

  if (opts.json) {
    const out: Record<string, Record<string, { ok: boolean; detail: string; recorded: boolean }>> = {};
    for (const name of profileNames) {
      out[name] = {};
      for (const surface of ALL) {
        const recorded = !!state.profiles[name].surfaces[surface];
        const live = inspect(surface, name);
        out[name][surface] = { ok: live.ok, detail: live.detail, recorded };
      }
    }
    console.log(JSON.stringify({ profiles: out }, null, 2));
    return;
  }

  if (profileNames.length === 0) {
    console.log(kleur.gray('No profiles installed. Run `agent-toolbox install <profile>`.'));
    return;
  }

  for (const name of profileNames) {
    console.log(kleur.bold(`\nProfile: ${name}`));
    for (const surface of ALL) {
      const recorded = state.profiles[name].surfaces[surface];
      const live = inspect(surface, name);
      const icon = live.ok
        ? kleur.green('✓')
        : recorded
          ? kleur.yellow('!')
          : kleur.gray('–');
      const label = surface.padEnd(16);
      const detail = live.ok ? live.detail : recorded ? `state drift: ${recorded.detail}` : 'not installed';
      console.log(`  ${icon} ${label} ${kleur.gray(detail)}`);
    }
  }
}

function inspect(surface: SurfaceName, profile: string): { ok: boolean; detail: string } {
  switch (surface) {
    case 'claude': {
      const file = claudeUserMd();
      if (!fs.existsSync(file)) return { ok: false, detail: `${file} missing` };
      const content = fs.readFileSync(file, 'utf8');
      const marker = `<!-- agent-toolbox:${profile}:begin -->`;
      return content.includes(marker)
        ? { ok: true, detail: file }
        : { ok: false, detail: `no marker in ${file}` };
    }
    case 'copilot-vscode': {
      const file = path.join(vscodePromptsDir(), `${profile}.agent.md`).split(path.sep).join('/');
      return fs.existsSync(file)
        ? { ok: true, detail: file }
        : { ok: false, detail: `${file} missing` };
    }
    case 'copilot-cli': {
      const expected = path.join(userGeneratedRoot(), profile).split(path.sep).join('/');
      const envVal = process.env.COPILOT_CUSTOM_INSTRUCTIONS_DIRS ?? '';
      if (envVal.split(/[;:]/).some((p) => p === expected)) {
        return { ok: true, detail: `env points at ${expected}` };
      }
      return {
        ok: false,
        detail: `COPILOT_CUSTOM_INSTRUCTIONS_DIRS does not contain ${expected}`,
      };
    }
    case 'codex': {
      const target = path.join(codexHome(), 'AGENTS.override.md').split(path.sep).join('/');
      if (!fs.existsSync(target)) return { ok: false, detail: `${target} missing` };
      try {
        const stat = fs.lstatSync(target);
        if (stat.isSymbolicLink()) {
          const link = fs.readlinkSync(target);
          return { ok: true, detail: `${target} → ${link}` };
        }
      } catch {
        /* ignore */
      }
      const body = fs.readFileSync(target, 'utf8');
      if (body.includes(`agent-toolbox:${profile}:codex`) || body.includes('GENERATED by agent-toolbox')) {
        return { ok: true, detail: `${target} (copy)` };
      }
      return { ok: false, detail: `${target} not owned by agent-toolbox` };
    }
  }
}
