import fs from 'node:fs';
import path from 'node:path';
import YAML from 'yaml';
import { ProfileSource, resolveShared, resolveStack } from '../profiles.js';
import { vscodePromptsDir } from '../paths.js';
import { GeneratedArtifacts } from '../generator.js';
import type { SurfaceResult } from './claude.js';
import {
  discoverStackAssets,
  namespacedName,
  hashFile,
  normalise,
  deployOne,
  DeployOutcome,
} from '../stack-assets.js';
import {
  removeDeployedAssets,
  listDeployedAssets,
  isPathClaimedByOtherProfile,
  DeployedAsset,
} from '../state.js';

export interface CopilotVsCodeOptions {
  vscodeSettings?: string;
  dryRun?: boolean;
  uninstall?: boolean;
}

interface BundleFile {
  src: string;
  basename: string;
  description?: string;
  role: 'project-context' | 'shared' | 'stack';
}

/**
 * Compute the list of guideline files that need to live as siblings of the
 * Copilot agent file. VS Code Copilot only resolves Markdown links with
 * RELATIVE paths to files reachable from the prompts folder — absolute paths
 * are silently ignored. So we deploy the project-context, every shared
 * guideline, and every stack guideline file into a sibling bundle dir, then
 * link them by relative path from the agent file.
 */
function copilotBundleFiles(profile: ProfileSource): BundleFile[] {
  const files: BundleFile[] = [];

  if (profile.manifest.projectContext) {
    const ctx = path.join(profile.dir, profile.manifest.projectContext);
    if (!fs.existsSync(ctx)) {
      throw new Error(`project_context not found: ${ctx}`);
    }
    files.push({
      src: ctx,
      basename: path.basename(profile.manifest.projectContext),
      description: readFrontmatterDescription(ctx),
      role: 'project-context',
    });
  }

  for (const sharedName of profile.manifest.shared) {
    const src = resolveShared(sharedName);
    files.push({
      src,
      basename: sharedName,
      description: readFrontmatterDescription(src),
      role: 'shared',
    });
  }

  for (const stackName of profile.manifest.stacks) {
    const stackDir = resolveStack(stackName);
    const stackFiles = fs
      .readdirSync(stackDir)
      .filter((f) => f.endsWith('.md'))
      .sort();
    for (const f of stackFiles) {
      const src = path.join(stackDir, f);
      files.push({
        src,
        basename: `${stackName}--${f}`,
        description: readFrontmatterDescription(src),
        role: 'stack',
      });
    }
  }

  return files;
}

function stripFrontmatter(content: string): string {
  return content.replace(/^---\s*\n[\s\S]*?\n---\s*\n?/, '');
}

function composeCopilotAgentMd(profile: ProfileSource, files: BundleFile[]): string {
  const cm = profile.manifest.copilot;
  const name = cm.name ?? profile.name;
  const description = cm.description ?? profile.manifest.description ?? `${profile.name} agent`;

  const lines: string[] = [];
  lines.push('---');
  lines.push(`name: ${name}`);
  lines.push(`description: ${description}`);
  lines.push('---');
  lines.push('');
  lines.push('<!-- GENERATED by agent-toolbox — do not edit -->');
  lines.push(`<!-- profile: ${profile.name} -->`);
  lines.push('');
  lines.push(`# ${name}`);
  lines.push('');
  lines.push(
    `You are the **${profile.name}** agent. The sections below are the authoritative rules for this profile. Apply them literally — never rely on generic knowledge when a rule exists.`
  );
  lines.push('');

  // Copilot VS Code does not follow Markdown links to load external files,
  // so we inline every guideline body verbatim. The trade-off vs Claude (which
  // lazy-loads via @-imports) is a fatter agent file but a guarantee that the
  // agent actually sees the rules. Frontmatter is stripped from each inlined
  // file to avoid YAML noise inside the body.
  const ctxFile = files.find((f) => f.role === 'project-context');
  if (ctxFile) {
    lines.push('---');
    lines.push('');
    lines.push(`# Project context — ${ctxFile.basename}`);
    lines.push('');
    lines.push(stripFrontmatter(fs.readFileSync(ctxFile.src, 'utf8')).trim());
    lines.push('');
  }

  const otherFiles = files.filter((f) => f.role !== 'project-context');
  for (const f of otherFiles) {
    lines.push('---');
    lines.push('');
    lines.push(`# ${f.role === 'shared' ? 'Shared' : 'Stack'} — ${f.basename}`);
    lines.push('');
    lines.push(stripFrontmatter(fs.readFileSync(f.src, 'utf8')).trim());
    lines.push('');
  }

  return lines.join('\n');
}

function readFrontmatterDescription(file: string): string | undefined {
  const content = fs.readFileSync(file, 'utf8');
  const match = content.match(/^---\s*\n([\s\S]*?)\n---/);
  if (!match) return undefined;
  try {
    const fm = YAML.parse(match[1]) ?? {};
    if (typeof fm.description === 'string') return fm.description;
  } catch {
    // ignore malformed frontmatter
  }
  return undefined;
}

export function runCopilotVscode(
  profile: ProfileSource,
  _artifacts: GeneratedArtifacts,
  opts: CopilotVsCodeOptions = {}
): SurfaceResult {
  const promptsDir = vscodePromptsDir(opts.vscodeSettings);
  const agentFile = path.join(promptsDir, `${profile.name}.agent.md`).split(path.sep).join('/');
  const legacyBundleDir = path.join(promptsDir, profile.name).split(path.sep).join('/');

  if (opts.uninstall) {
    const agentExists = fs.existsSync(agentFile);
    const legacyExists = fs.existsSync(legacyBundleDir);
    if (!agentExists && !legacyExists) {
      return { surface: 'copilot-vscode', action: 'noop', detail: `nothing to remove at ${agentFile}` };
    }
    if (opts.dryRun) {
      return {
        surface: 'copilot-vscode',
        action: 'planned',
        detail: `would remove ${agentFile}`,
      };
    }
    if (agentExists) fs.rmSync(agentFile);
    if (legacyExists) fs.rmSync(legacyBundleDir, { recursive: true, force: true });
    return {
      surface: 'copilot-vscode',
      action: 'remove',
      detail: `removed ${agentFile}`,
    };
  }

  const bundleFiles = copilotBundleFiles(profile);
  const newAgentBody = composeCopilotAgentMd(profile, bundleFiles);

  const existingAgent = fs.existsSync(agentFile) ? fs.readFileSync(agentFile, 'utf8') : '';
  const upToDate = existingAgent === newAgentBody && !fs.existsSync(legacyBundleDir);

  if (upToDate) {
    return { surface: 'copilot-vscode', action: 'noop', detail: `already up to date at ${agentFile}` };
  }

  if (opts.dryRun) {
    return {
      surface: 'copilot-vscode',
      action: 'planned',
      detail: `would write ${agentFile} (inlining ${bundleFiles.length} guideline${bundleFiles.length === 1 ? '' : 's'})`,
    };
  }

  fs.mkdirSync(promptsDir, { recursive: true });
  fs.writeFileSync(agentFile, newAgentBody, 'utf8');

  // Clean up any legacy bundle dir from the previous link-based deployment.
  if (fs.existsSync(legacyBundleDir)) {
    fs.rmSync(legacyBundleDir, { recursive: true, force: true });
  }

  return {
    surface: 'copilot-vscode',
    action: existingAgent ? 'update' : 'append',
    detail: `wrote ${agentFile} (inlined ${bundleFiles.length} guideline${bundleFiles.length === 1 ? '' : 's'})`,
  };
}

/**
 * Deploy per-stack Copilot VS Code assets (prompt files + chat modes) for a
 * profile. Runs after `runCopilotVscode()` inside the install command.
 */
export function deployCopilotVscodeAssets(
  profile: ProfileSource,
  opts: CopilotVsCodeOptions = {}
): SurfaceResult {
  const promptsDir = vscodePromptsDir(opts.vscodeSettings);
  let added = 0;
  let updated = 0;
  let unchanged = 0;
  let swept = 0;
  let planned = 0;

  const expectedPaths = new Set<string>();

  for (const stackName of profile.manifest.stacks) {
    const stackDir = resolveStack(stackName);
    const assets = discoverStackAssets(stackDir);

    const files: Array<{ src: string; kind: 'prompt' | 'chatmode' }> = [
      ...assets.prompts.map((src) => ({ src, kind: 'prompt' as const })),
      ...assets.chatModes.map((src) => ({ src, kind: 'chatmode' as const })),
    ];

    for (const { src, kind } of files) {
      const dst = normalise(path.join(promptsDir, namespacedName(stackName, path.basename(src))));
      expectedPaths.add(dst);
      const outcome: DeployOutcome = deployOne({
        profile: profile.name,
        stack: stackName,
        surface: 'copilot-vscode',
        kind,
        src,
        dst,
        hashFn: () => hashFile(src),
        copyFn: () => {
          fs.mkdirSync(path.dirname(dst), { recursive: true });
          fs.copyFileSync(src, dst);
        },
        dryRun: opts.dryRun,
      });
      switch (outcome) {
        case 'added':
          added++;
          break;
        case 'updated':
          updated++;
          break;
        case 'unchanged':
          unchanged++;
          break;
        case 'planned':
          planned++;
          break;
      }
    }
  }

  // Sweep: remove deployed assets whose source was deleted or renamed.
  const referencedStacks = new Set(profile.manifest.stacks);
  const copilotAssets = listDeployedAssets(
    profile.name,
    (a) => a.surface === 'copilot-vscode' && referencedStacks.has(a.stack)
  );
  for (const a of copilotAssets) {
    if (expectedPaths.has(a.path)) continue;
    if (opts.dryRun) {
      planned++;
      continue;
    }
    if (!isPathClaimedByOtherProfile(a.path, profile.name)) {
      try {
        fs.rmSync(a.path, { force: true });
      } catch {
        // ENOENT-safe
      }
    }
    removeDeployedAssets(
      profile.name,
      (x) => x.surface === 'copilot-vscode' && x.path === a.path
    );
    swept++;
  }

  if (opts.dryRun) {
    if (planned === 0 && swept === 0) {
      return {
        surface: 'copilot-vscode:assets',
        action: 'noop',
        detail: 'no stack assets to deploy',
      };
    }
    return {
      surface: 'copilot-vscode:assets',
      action: 'planned',
      detail: `would deploy ${planned}, sweep ${swept}`,
    };
  }

  const touched = added + updated + swept;
  if (touched === 0 && unchanged === 0) {
    return {
      surface: 'copilot-vscode:assets',
      action: 'noop',
      detail: 'no stack assets to deploy',
    };
  }
  if (touched === 0) {
    return {
      surface: 'copilot-vscode:assets',
      action: 'noop',
      detail: `${unchanged} asset${unchanged === 1 ? '' : 's'} already up to date`,
    };
  }
  const parts: string[] = [];
  if (added) parts.push(`${added} new`);
  if (updated) parts.push(`${updated} updated`);
  if (unchanged) parts.push(`${unchanged} unchanged`);
  if (swept) parts.push(`${swept} swept`);
  return {
    surface: 'copilot-vscode:assets',
    action: added > 0 ? 'append' : updated > 0 ? 'update' : 'remove',
    detail: `copilot-vscode assets: ${parts.join(', ')}`,
  };
}

export function removeCopilotVscodeAssets(
  profile: ProfileSource,
  opts: CopilotVsCodeOptions = {},
  predicate: (a: DeployedAsset) => boolean = () => true
): SurfaceResult {
  const targets = listDeployedAssets(
    profile.name,
    (a) => a.surface === 'copilot-vscode' && predicate(a)
  );
  if (targets.length === 0) {
    return {
      surface: 'copilot-vscode:assets',
      action: 'noop',
      detail: 'no copilot-vscode assets tracked',
    };
  }
  if (opts.dryRun) {
    return {
      surface: 'copilot-vscode:assets',
      action: 'planned',
      detail: `would remove ${targets.length} copilot-vscode asset${targets.length === 1 ? '' : 's'}`,
    };
  }
  let removed = 0;
  for (const a of targets) {
    if (!isPathClaimedByOtherProfile(a.path, profile.name)) {
      try {
        fs.rmSync(a.path, { force: true });
      } catch {
        // ENOENT-safe
      }
    }
    removed++;
  }
  removeDeployedAssets(profile.name, (a) => a.surface === 'copilot-vscode' && predicate(a));
  return {
    surface: 'copilot-vscode:assets',
    action: 'remove',
    detail: `removed ${removed} copilot-vscode asset${removed === 1 ? '' : 's'}`,
  };
}
